### ISSUE TITLE
Multicall Error

### ISSUE THREAD

**Issue by azvast** [solidquant/whack-a-mole#2]
After installing all the packages and ran main.py, I get this error in ubuntu 20.04. But it works well in Windows 10.
I think the problem is that MultiCall has another asyncio creation in the package.

```dev@ip-172-31-10-3:~/arbmon$ python3 main.py
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dev/arbmon/strategies/dex_arb_base.py", line 57, in dex_stream_process
    dex = DEX({chain: RPC_ENDPOINTS[chain]},
  File "/home/dev/arbmon/data/dex.py", line 431, in __init__
    self.load()
  File "/home/dev/arbmon/data/dex.py", line 128, in load
    self._load_pool_data()
  File "/home/dev/arbmon/data/dex.py", line 166, in _load_pool_data
    **multicall()
  File "/home/dev/.local/lib/python3.10/site-packages/multicall/multicall.py", line 58, in __call__
    response = await_awaitable(self)
  File "/home/dev/.local/lib/python3.10/site-packages/multicall/utils.py", line 73, in await_awaitable
    return get_event_loop().run_until_complete(awaitable)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 584, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

I can find another way to get values concurrently in web3.js.
```
var contract = new web3.eth.Contract(abi, address);

var batch = new web3.BatchRequest();
batch.add(web3.eth.getBalance.request('0x0000000000000000000000000000000000000000', 'latest', callback));
batch.add(contract.methods.balance(address).call.request({from: '0x0000000000000000000000000000000000000000'}, callback2));
batch.execute();
```
https://web3js.readthedocs.io/en/v1.7.0/web3.html#id11

**Comment by solidquant** [comment]
Hey, thanks for the catch. I was mostly on my mac so I must have missed it.
I'll give it a quick look on my Ubuntu machine!

**Comment by azvast** [comment]
Thanks, it's working well on ubuntu.
